### ISSUE TITLE
"Un-Force user text-align in div,p tags in KePubs" break alignment changes

### ISSUE THREAD

**Issue by zhengbli** [pgaskin/kobopatch-patches#109]
After enabling this patch, I can't change alignment anymore, the book stays whatever the publisher intended and never changed. Tried on about 10+ different books, none worked. 

version: 4.33.19759

**Comment by jackiew1** [comment]
> After enabling this patch, I can't change alignment anymore, the book stays whatever the publisher intended and never changed. Tried on about 10+ different books, none worked.

I think you haven't understood what this patch is for. I just answered a [similar question here](https://www.mobileread.com/forums/showpost.php?p=4246505&postcount=35).
