### ISSUE TITLE
Missing patch for enabling stylus on kepubs

### ISSUE THREAD

**Issue by ScrambleTheRamble** [pgaskin/kobopatch-patches#111]
Maybe I'm doing something wrong, but the patch mentioned [here](https://github.com/pgaskin/kepubify/issues/66) seems to be missing from the patches available for the latest firmware for the Kobo Elipsa?

**Comment by ScrambleTheRamble** [comment]
Hi, thx for the reply, I did notice that comment but wasn't sure what was implied as it seems to not work on my .kepubs, I'll do some more tests and see just why it fails here. 

Feel free to close the ticket as it's not an issue with kobopatch in this case.

**Comment by pgaskin** [comment]
What's KCC?
