### ISSUE TITLE
Missing Clara2E comment labels

### ISSUE THREAD

**Issue by jackiew1** [pgaskin/kobopatch-patches#118]
@pgaskin 

It's been brought to my attention that we forgot to add the Clara2E to the various comment labels in `nickel.yaml` and `libnickel.so.1.0.0.yaml`.

I've just updated all the `nickel.yaml` occurrences to add Clara2E to wherever ClaraHD currently appears. However, I'm not 100% sure whether the same logic applies to occurrences in `libnickel.so.1.0.0.yaml`.

I think it's only `Custom font sizes` and the 3 keyboard patches which are affected.

**Comment by pgaskin** [comment]
This appears to have been done in af14b60bd4a4218b8cf19613ec84c2742d5d3068 97a17274967e5377086cf538fe7c9eadee1f3702 0903a8c0dc2b2c82ec6819f97d202e5d9276e728 976bfcb8c2bbfe28e79ccf33c2749e4ff5515c8e, which has been released in [`v81`](https://github.com/pgaskin/kobopatch-patches/releases/v81).
