### ISSUE TITLE
Patches for fw 4.38.21908

### ISSUE THREAD

**Issue by jackiew1** [pgaskin/kobopatch-patches#126]
@pgaskin 

Hi, Patrick. I'm not sure where else to post this. I've had a quick look at 4.38.21908. There are at least 2 patches which need some work:
-  `My 24 line spacing values` - no idea how difficult this is to fix
-  `Dictionary text font-family/font-size/line-height` - this looks like a simple fix which I can do as soon as there are some version 4.38.21908 yamls for me to update.

**Comment by shermp** [comment]
I don't have myself setup to try testing patches, but the `24 line` patch may be a simple offset change.

Try setting the `Rel` field in `BaseAddress:  {Sym: "ReadingSettings::lineHeightScalars() const", Rel: 84} # starting at first QList<double>::append(double const&)` to `40`.

**Comment by jackiew1** [comment]
> Try setting the `Rel` field in `BaseAddress: {Sym: "ReadingSettings::lineHeightScalars() const", Rel: 84} # starting at first QList<double>::append(double const&)` to `40`.

@shermp 
Thanks for looking. Unfortunately the patch still doesn't run after making this change. The new error message is:
```Error: could not apply patches: error applying patch file 'src/libnickel.so.1.0.0.yaml': could not apply patch "My 24 line spacing values": line 50: inst 5: ReplaceBytes: could not find specified bytes```

Perhaps more, or different, offsets need to be changed?

In case it's relevant ... the patch `My 10 line spacing values` still runs without error and still works as expected on a KA1. This patch also starts with the same BaseAddress instruction as `My 24 line spacing values`, namely:
```BaseAddress:  {Sym: "ReadingSettings::lineHeightScalars() const", Rel: 84}```

**Comment by pgaskin** [comment]
I'll take a look soon; I've been away for the last week.

**Comment by pgaskin** [comment]
Closing in favour of #127.
