### ISSUE TITLE
 Have a different brightness icon when light is off 

### ISSUE THREAD

**Issue by hub2git** [pgaskin/kobopatch-patches#37]
On the Kobo Forma, the brightness icon is the same whatever the  brightness level, whether 0%, 1%... 5%... 50%... 100%. It's an icon of a  sun. 

I'd like to request the Kobo patch team to either:
A) replace the sun icon with a different icon when the light is completely off (for example, a circle that is filled with black) 
or
 B) create something beside the sun icon to indicate the light is completely off (for example,the word "0% light")  

Rationale for this request: occasionally, when I'm in a completely dark  room, I turn on the brightness from 0% to 1%. The next day, in the  daytime, I read on my Kobo Forma forgetting that the brightness is on,  and wading battery because I don't need the light at all in the daytime.

**Comment by geek1011** [comment]
I won't be implementing this. Although it is a relatively simple thing to do, it would require modifying the UI and adding resources, which is quite time consuming.

**Comment by hub2git** [comment]
Ok. Thanks for your reply. Who can I bring this request to?

**Comment by geek1011** [comment]
I don't think there's anybody else who has experience with this and the interest to work on it at the moment.

**Comment by hub2git** [comment]
@geek1011, thanks again for your response. Maybe we can create a fund or a target dollar-figure for each request. Then for those that meet the minimum dollar-figure can get worked on. I think this is called "bounty". 
Anyway, I appreciate all your work on the various patches. :)
