### ISSUE TITLE
ePub fixed/adjustable top/bottom margins

### ISSUE THREAD

**Issue by Havner** [pgaskin/kobopatch-patches#41]
Hi,
Will this patch be updated for 4.18? I did not see a TODO/issue for it like with some others.

**Comment by geek1011** [comment]
It would have to be rewritten from scratch, as too much has changed over the last few versions.

**Comment by geek1011** [comment]
I'm not planning to rewrite this patch myself, and I don't see too much interest in it (it might not even be required anymore). I'm going to close this issue for now.
