### ISSUE TITLE
Rewrite font scale patches for 4.28.18220+

### ISSUE THREAD

**Issue by pgaskin** [pgaskin/kobopatch-patches#96]
See #92 and #94.

**Comment by shermp** [comment]
Ok, patch has been updated to find `QScreen::logicalDotsPerInchX()` using `FindInstBLX`, and added to 4.30.18838

**Comment by pgaskin** [comment]
Minor nitpick: we generally use MR usernames rather than GH ones for and within the patch files themselves to avoid confusion.

Can you open a PR for your branch? I'll review it and merge it for the release if I have time tonight and it works on my devices.

**Comment by shermp** [comment]
Yeah, I can make those changes.

**Comment by shermp** [comment]
> Yeah, I can make those changes.

And done.

**Comment by pgaskin** [comment]
I've merged the unify font scales patch so people can try it in v73. Thanks @shermp!

P.S. I made a typo in the commit message quotes... oh, well...

**Comment by pgaskin** [comment]
@shermp: I've done some cleanup in a2ffddfe699e07bae4c459f09fc9287361e185b2.

**Comment by shermp** [comment]
> @shermp: I've done some cleanup in [a2ffddf](https://github.com/pgaskin/kobopatch-patches/commit/a2ffddfe699e07bae4c459f09fc9287361e185b2).

Oh, thanks. I couldn't quite figure out how the relative offsets was supposed to work, so thanks for doing that.

Although I tried, I never could figure out the magic demangled symbol that would make kobopatch happy, so yet another thanks! I had forgotten about the `const` qualifier.

**Comment by shermp** [comment]
Just wondering, to avoid potential confusion, should the patch be renamed to something like `Unify kepub and epub font sizes`?

**Comment by pgaskin** [comment]
@shermp's new `Unify font sizes` patch has been released in v73. I'm going to leave this issue open until we get some feedback and can confirm this can replace the old font scale patches.

> Just wondering, to avoid potential confusion, should the patch be renamed to something like Unify kepub and epub font sizes?

Too late for that now.

**Comment by pgaskin** [comment]
Since the updated `Custom font sizes` and new `Unify font sizes` patches seem to cover everything and have received positive feedback on MR over the last month, I'm going to close this issue.

**Comment by JSWolf** [comment]
The original patch **ePub uniform font scale:** worked by making the KePub font size match that of the ePub font size. For those that need/want larger font sizes, this worked best. This patch works by reducing the ePub font size. Can this the swapped around so it works like the original patch to make the KePub font size larger to match the ePub font size?
